"""initial schema with PostGIS

Baselines the full schema from the ORM metadata so the database always matches
``app/models``. Subsequent migrations should be autogenerated deltas.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-12
"""

from __future__ import annotations

from alembic import op
from app.models import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    # PostGIS provides GEOMETRY types + spatial indexing used by sellers/delivery.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # Create every table, enum, and spatial index defined on the ORM metadata.
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
